### PR TITLE
Replaced Parallel Programming course

### PR DESCRIPTION
**Pull request by ivaluexrays**
Replaced Scala parallel programming with Java parallel programming course, because we don't have any Scala courses in the curriculum.

### CODE REVIEW

**Comment by hckme4** [comment]
needs a new patch to fix conflicts.

**Comment by ivaluexrays** [comment]
I don't know how to do that

**Comment by hckme4** [comment]
> I don't know how to do that

just open the commit and edit it.

**Review by hckme4 — COMMENTED** [review]
Looks good now

**Pull request merged**
