### PR TITLE
First Curriculum Rewrite

### PR DESCRIPTION
**Pull request by hckme4**
Moved all systems design and theory portions of the curriculum to relevant places for information security. trimmed the ethics section, moved databases so it's higher in rank order of importance in the curriculum, created our own Github badges, began rewriting the Final Project Section.

### CODE REVIEW

**Comment by unclamped** [comment]
Checking this PR from my phone, noticed two things so far. It might be a good idea to cut out the server invites until we make an NXFury server, as these still point to OSSU's. 
I also noticed that the badge has NXFury typed completely in caps, is this intended?
And finally, I suggest that we pass the readme through some grammar checker like Grammarly (closed source), or any other open source alternatives if there's any available

**Comment by unclamped** [comment]
oh, one more thing, the code of conduct is still named after OSSU's

**Comment by hckme4** [comment]
I intended to full-caps the badge, and I agree the next phase should be to muck with the server invites so they're not valid (we can replace them later). I Intend to work on the Code of Conduct tomorrow.

**Comment by hckme4** [comment]
maybe in future commits, we should add a smidge more vertical space so it's easier to read?

**Comment by unclamped** [comment]
Eh, it looks just fine to me. We should wait for more feedback from other reviewers though.

**Comment by ivaluexrays** [comment]
Yeah looks good, I'll add in the cryptography content tomorrow.

**Pull request merged**
